spring:
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
logging:
  level:
    ROOT: warn
    org.hibernate: DEBUG
    org:
      springframework:
        data:
          jpa: DEBUG
#debug: true
