spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring
    username: spring
    password: spring
  jpa:
    properties:
      hibernate:
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false